.ig
 * Bu kılavuz sayfası Türkçe Linux Belgelendirme Projesi (TLBP) tarafından
 * XML belgelerden derlenmiş olup manpages-tr paketinin parçasıdır:
 * https://github.com/TLBP/manpages-tr
 *
 * Özgün Belgenin Lisans ve Telif Hakkı bilgileri:
 *
 * Copyright 1991 - 1994, Julianne Frances Haugh
 * Copyright 1996 - 2000, Marek Michałkiewicz
 * Copyright 2000 - 2006, Tomasz Kłoczko
 * Copyright 2007 - 2011, Nicolas François
 * All rights reserved.
 *
 * Redistribution and use in source and binary forms, with or without
 * modification, are permitted provided that the following conditions
 * are met:
 * 1. Redistributions of source code must retain the above copyright
 *    notice, this list of conditions and the following disclaimer.
 * 2. Redistributions in binary form must reproduce the above copyright
 *    notice, this list of conditions and the following disclaimer in the
 *    documentation and/or other materials provided with the distribution.
 * 3. Neither the name of Julianne F. Haugh nor the names of its contributors
 *    may be used to endorse or promote products derived from this software
 *    without specific prior written permission.
 *
 * THIS SOFTWARE IS PROVIDED BY JULIE HAUGH AND CONTRIBUTORS ’’AS IS’’ AND
 * ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
 * IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE
 * ARE DISCLAIMED.  IN NO EVENT SHALL JULIE HAUGH OR CONTRIBUTORS BE LIABLE
 * FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL
 * DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS
 * OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION)
 * HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT
 * LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY
 * OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF
 * SUCH DAMAGE.
..
.\" Derlenme zamanı: 2022-12-08T19:24:12+03:00
.TH "GROUPDEL" 8 "Şubat 2022" "Shadow-utils 4.11.1" "Sistem Yönetim Komutları"
.\" Sözcükleri ilgisiz yerlerden bölme (disable hyphenation)
.nh
.\" Sözcükleri yayma, sadece sola yanaştır (disable justification)
.ad l
.PD 0
.SH İSİM
groupdel - bir grubu siler
.sp
.SH KULLANIM
.IP \fBgroupdel\fR 9
[\fIseçenekler\fR] \fIGRUP\fR
.sp
.PP
.sp
.SH "AÇIKLAMA"
\fBgroupdel\fR komutu, sistem hesap dosyalarını düzenler ve \fIGRUP\fR olarak belirtilen gruba ait bütün girdileri siler. Silinmek istenen grup, sistemde varolmalıdır.
.sp
.SH "SEÇENEKLER"
.TP 4
\fB-f\fR, \fB--force\fR
Bu seçenek, \fBgroupadd\fR komutunun eklemeye çalıştığı grup sistemde zaten var ise, başarılı durum koduyla çıkmasını sağlar. \fB-g\fR seçeneği ile kullanıldığında ve belirtilen \fIgrup-kimliği\fR mevcutsa diğer (eşsiz) grup kimliği seçilir (yani \fB-g\fR kapatılır).
.sp
.TP 4
\fB-h\fR, \fB--help\fR
Yardım metnini gösterir ve çıkar.
.sp
.TP 4
\fB-R\fR, \fB--root\fR \fICHROOT_DİZİNİ\fR
Değişiklikleri \fICHROOT_DİZİNİ\fRnde uygular ve \fICHROOT_DİZİNİ\fRndeki yapılandırma dosyaları kullanılır.
.sp
.TP 4
\fB-P\fR, \fB--prefix\fR \fIPREFIX_DİZİNİ\fR
Değişiklikleri \fIPREFIX_DİZİNİ\fRnde uygular ve \fIPREFIX_DİZİNİ\fRndeki yapılandırma dosyaları kullanılır. Bu seçenek chroot yapmaz ve çapraz derlemeye hazırlık için tasarlanmamıştır. Bazı sınırlamalar: NIS ve LDAP kullanıcı ve grupları doğrulanmaz. PAM kimlik kanıtlaması konak dosyalarını kulllanılır. SELinux desteklenmez.
.sp
.PP
.sp
.SH "YETERSİZLİKLER"
Varolan herhangi bir kullanıcının birincil grubunu silemeyebilirsiniz. Grubu silmeden önce bu kullanıcıyı sistemden kaldırmak zorundasınız.
.sp
Silme işleminden sonra, silinen grup numarasına ait herhangi bir dosya kalmadığından emin olmak için bütün dosya sistemlerini kontrol etmelisiniz.
.sp
.SH "YAPILANDIRMA"
Bu aracın davranışını değiştirmek için \fI/etc/login.defs\fR dosyasında bulunan aşağıdaki değişkenler kullanılabilir:
.sp
.TP 4
\fBMAX_MEMBERS_PER_GROUP\fR (tamsayı)
Grup girdisi başına azami üye sayısı. Bu değere ulaşıldığında, \fI/etc/group\fR içinde (aynı ad, aynı parola ve aynı grup kimliği ile) yeni bir grup girdisi (satır) başlatılır
.sp
Öntanımlı değer 0 olup, grup üyelerinin sayısı için bir azami sınır olmadığı anlamına gelir.
.sp
Bu özellik (grup bölme) grup dosyasındaki satır uzunluğunu sınırlamayı sağlar. NIS grupları için satırların 1024 karakterden uzun olmamasından emin olunmasını sağlamak için yararlıdır.
.sp
Bir sınır belirtmek gerekliyse, 25 iyidir.
.sp
Grup bölme (bu seçenek) tüm araçlarda desteklenmeyebilir (Shadow araçlarında bile). Gerçekten ihtiyaç duyulmadıkça bu seçenek kullanılmamalıdır.
.sp
.PP
.sp
.SH "İLGİLİ DOSYALAR"
.RS 4
.nf
\fB/etc/group\fR   - grupların hesap bilgileri
\fB/etc/gshadow\fR - güvenli grup bilgileri
.fi
.sp
.RE
.sp
.SH "ÇIKIŞ DURUMU"
\fBgroupdel\fR komutu şu değerlerle çıkar:
.sp
.TP 4
\fI0\fR
başarılı
.sp
.TP 4
\fI2\fR
geçersiz sözdizimi
.sp
.TP 4
\fI6\fR
böyle bir grup yok
.sp
.TP 4
\fI8\fR
kullanıcının birincil grubu silinemiyor
.sp
.TP 4
\fI10\fR
\fI/etc/group\fR dosyası güncellenemiyor
.sp
.PP
.sp
.SH "İLGİLİ BELGELER"
\fBchfn\fR(1), \fBchsh\fR(1), \fBpasswd\fR(1), \fBgpasswd\fR(1), \fBgroupadd\fR(8), \fBgroupmod\fR(8), \fBlogin.defs\fR(5), \fBuseradd\fR(8), \fBuserdel\fR(8), \fBusermod\fR(8).
.sp
.SH "ÇEVİREN"
© 2004 Yalçın Kolukısa
.br
© 2022 Nilgün Belma Bugüner
.br
Bu çeviri özgür yazılımdır: Yasaların izin verdiği ölçüde HİÇBİR GARANTİ YOKTUR.
.br
Lütfen, çeviri ile ilgili bildirimde bulunmak veya çeviri yapmak için https://github.com/TLBP/manpages-tr/issues adresinde "New Issue" düğmesine tıklayıp yeni bir konu açınız ve isteğinizi belirtiniz.
.sp
