.ig
 * Bu kılavuz sayfası Türkçe Linux Belgelendirme Projesi (TLBP) tarafından
 * XML belgelerden derlenmiş olup manpages-tr paketinin parçasıdır:
 * https://github.com/TLBP/manpages-tr
 *
..
.\" Derlenme zamanı: 2022-11-10T14:08:50+03:00
.TH "SUM" 1 "Eylül 2021" "GNU coreutils 9.0" "Kullanıcı Komutları"
.\" Sözcükleri ilgisiz yerlerden bölme (disable hyphenation)
.nh
.\" Sözcükleri yayma, sadece sola yanaştır (disable justification)
.ad l
.PD 0
.SH İSİM
sum - bir dosyadaki blok sayısını ve sağlama toplamını basar
.sp
.SH KULLANIM
.IP \fBsum\fR 4
[\fISEÇENEK\fR]... [\fIDOSYA\fR]...
.sp
.PP
.sp
.SH "AÇIKLAMA"
Her \fIDOSYA\fR’nın BSD sağlama toplamını (16 bit) ve blok sayısını yazar.
.sp
\fIDOSYA\fR belirtilmezse veya \fB-\fR olarak belirtilirse standart girdi okunur.
.sp
.TP 4
\fB-r\fR
BSD toplama algoritmasını (öntanımlıdır) kullanır, blok genişliğini 1K alır.
.sp
.TP 4
\fB-s\fR, \fB--sysv\fR
System V toplama algoritmasını kullanır, blok genişliğini 512 bayt alır
.sp
.TP 4
\fB--help\fR
Yardım iletisini görüntüler ve çıkar.
.sp
.TP 4
\fB--version\fR
Sürüm bilgilerini görüntüler ve çıkar.
.sp
.PP
.sp
.SH "YAZAN" 
Kayvan Aghaiepour ve David MacKenzie tarafından yazılmıştır.
.sp
.SH "GERİBİLDİRİM"
GNU coreutils sayfası: <http://www.gnu.org/software/coreutils/>
.sp
.SH "TELİF HAKKI"
Telif hakkı © 2021 Free Software Foundation, Inc. Lisans GPLv3+: GNU GPL sürüm 3 veya üstü <http://gnu.org/licenses/gpl.html> Bu bir özgür yazılımdır: yazılımı değiştirmek ve dağıtmakta özgürsünüz. Yasaların izin verdiği ölçüde HİÇBİR GARANTİ YOKTUR.
.sp
.SH "İLGİLİ BELGELER"
GNU coreutils sayfasında: <http://www.gnu.org/software/coreutils/sum>
.br
Veya sisteminizde: \fBinfo ’(coreutils) sum invocation’\fR
.sp
.SH "ÇEVİREN"
© 2006, 2022 Nilgün Belma Bugüner
.br
Bu çeviri özgür yazılımdır: Yasaların izin verdiği ölçüde HİÇBİR GARANTİ YOKTUR.
.br
Lütfen, çeviri ile ilgili bildirimde bulunmak veya çeviri yapmak için https://github.com/TLBP/manpages-tr/issues adresinde "New Issue" düğmesine tıklayıp yeni bir konu açınız ve isteğinizi belirtiniz.
.sp
